/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Auth;

/**
 *
 * @author rahul
 */
public class Certificate extends javax.swing.JFrame {

    /**
     * Creates new form Certificate
     */
    public Certificate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        courseNameLabel = new javax.swing.JLabel();
        companyNameLabel = new javax.swing.JLabel();
        monthLabel = new javax.swing.JLabel();
        dayLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        managerLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Auth/logo.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 58, 138, 41));

        jLabel1.setFont(new java.awt.Font("Waree", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("CourseWiz");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 39, -1, -1));

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel3.setText("Dashboard");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 64, -1, -1));

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel4.setText("Coaches");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 64, -1, -1));

        jLabel5.setText("🔔");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(876, 61, 36, -1));

        usernameLabel.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        usernameLabel.setText("Username");
        getContentPane().add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 150, 30));

        courseNameLabel.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        courseNameLabel.setText("Course Name");
        getContentPane().add(courseNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, -1, -1));

        companyNameLabel.setFont(new java.awt.Font("Source Code Pro", 1, 14)); // NOI18N
        companyNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        companyNameLabel.setText("CourseWiz");
        getContentPane().add(companyNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, -1, -1));

        monthLabel.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        monthLabel.setText("month");
        getContentPane().add(monthLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 550, -1, 20));

        dayLabel.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        dayLabel.setText("day");
        getContentPane().add(dayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, -1, -1));

        yearLabel.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        yearLabel.setText("year");
        getContentPane().add(yearLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 550, -1, -1));

        managerLabel.setFont(new java.awt.Font("Architects Daughter", 2, 14)); // NOI18N
        managerLabel.setText("Manager");
        getContentPane().add(managerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 620, 80, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Auth/certificate.jpg"))); // NOI18N
        jLabel2.setAlignmentY(0.0F);
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setIconTextGap(0);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 810, 624));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Certificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Certificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Certificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Certificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Certificate().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel companyNameLabel;
    private javax.swing.JLabel courseNameLabel;
    private javax.swing.JLabel dayLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel managerLabel;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
